/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * Accepts an image upload of a coffee cup and returns a mystical fortune interpretation using AI vision
 * @summary Analyze a coffee cup photo and generate a fortune
 */
export const GenerateFortuneBody = zod.object({
  image: zod.instanceof(File).describe("Photo of the coffee cup"),
});

export const GenerateFortuneResponse = zod.object({
  title: zod
    .string()
    .describe("A short mystical title for this fortune reading"),
  sections: zod.object({
    genel: zod.string().describe("General overview reading"),
    ask: zod.string().describe("Love and relationships reading"),
    para: zod.string().describe("Money and career reading"),
    yol: zod.string().describe("Path and journey reading"),
    saglik: zod.string().describe("Health reading"),
  }),
});
